version: '3'

services:

### MySQL ################################################
    mysql:
        container_name: "Jun_MySQL"
        image: 'mysql:${MYSQL_VERSION}'
        ports:
          - "${MYSQL_PORT}:3306"
          - "${MYSQL_PORT}0:33060"
        extra_hosts:
          - "dockerhost:${DOCKER_HOST_IP}"
        networks:
          - backend
        environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
        volumes:
          # - mysql:/var/lib/mysql
          - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        privileged: true
        restart: always

### Redis ################################################
    redis:
        container_name: "Jun_Redis"
        image: 'redis:${REDIS_VERSION}'
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ${DATA_PATH_HOST}/redis:/data
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend
        privileged: true
        restart: always


### phpMyAdmin ###########################################
    phpmyadmin:
        container_name: "Jun_PHPMyMySQL"
        # build: ./phpmyadmin
        image: "phpmyadmin/phpmyadmin"
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${MYSQL_TIMEZONE}
        ports:
            - "${PMA_PORT}:80"
        links:
            - mysql
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
            - "mysql.docker:192.168.99.101"
        depends_on:
            - "${PMA_DB_ENGINE}"
        networks:
            - backend
        privileged: true
        restart: always

    ### Memcached ############################################
    memcached:
        container_name: "Jun_Memcached"
        image: memcached:${MEMCACHED_VERSION}
        volumes:
            - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_HOST_PORT}:11211"
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        command: memcached
        networks:
            - backend
        privileged: true
        restart: always

networks:
    backend:
        driver: ${NETWORKS_DRIVER}
volumes:
    redis:
        driver: ${VOLUMES_DRIVER}
    mysql:
        driver: ${VOLUMES_DRIVER}
    phpmyadmin:
        driver: ${VOLUMES_DRIVER}
    memcached:
        driver: ${VOLUMES_DRIVER}
